// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package contact

import (
	"billionmail-core/api/contact"
)

type ControllerV1 struct{}

func NewV1() contact.IContactV1 {
	return &ControllerV1{}
}
