// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package campaign

import (
	"billionmail-core/api/campaign"
)

type ControllerV1 struct{}

func NewV1() campaign.ICampaignV1 {
	return &ControllerV1{}
}
