// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package subscribe_list

import (
	"billionmail-core/api/subscribe_list"
)

type ControllerV1 struct{}

func NewV1() subscribe_list.ISubscribeListV1 {
	return &ControllerV1{}
}
