// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package languages

import (
	"billionmail-core/api/languages"
)

type ControllerV1 struct{}

func NewV1() languages.ILanguagesV1 {
	return &ControllerV1{}
}
