// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package batch_mail

type ControllerV1 struct{}

func NewV1() *ControllerV1 {
	return &ControllerV1{}
}
