// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package rbac

import (
	"billionmail-core/api/rbac"
)

// ControllerV1 RBAC controller
type ControllerV1 struct{}

// NewV1 creates RBAC v1 controller
func NewV1() rbac.IRbacV1 {
	return &ControllerV1{}
}
