// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package abnormal_recipient

import (
	"billionmail-core/api/abnormal_recipient"
)

type ControllerV1 struct{}

func NewV1() abnormal_recipient.IAbnormalRecipientV1 {
	return &ControllerV1{}
}
