// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package mail_services

import (
	"billionmail-core/api/mail_services"
)

type ControllerV1 struct{}

func NewV1() mail_services.IMailServicesV1 {
	return &ControllerV1{}
}
