// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package domains

import (
	"billionmail-core/api/domains"
)

type ControllerV1 struct{}

func NewV1() domains.IDomainsV1 {
	return &ControllerV1{}
}
