// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package domains

import (
	"context"

	"billionmail-core/api/domains/v1"
)

type ControllerV1 struct{}

func New() *ControllerV1 {
	return &ControllerV1{}
}
