/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BtCharts: typeof import('./../src/components/base/bt-charts/index.vue')['default']
    BtCloseBtn: typeof import('./../src/components/base/bt-close-btn/index.vue')['default']
    BtConfigProvider: typeof import('./../src/components/ui/bt-config-provider/index.vue')['default']
    BtForm: typeof import('./../src/components/ui/bt-form/index.vue')['default']
    BtModal: typeof import('./../src/components/ui/bt-modal/index.vue')['default']
    BtSearch: typeof import('./../src/components/base/bt-search/index.vue')['default']
    BtTableLayout: typeof import('./../src/components/base/bt-table-layout/index.vue')['default']
    BtTablePage: typeof import('./../src/components/ui/bt-table-page/index.vue')['default']
    BtTablePassword: typeof import('./../src/components/base/bt-table-password/index.vue')['default']
    BtTabs: typeof import('./../src/components/ui/bt-tabs/index.vue')['default']
    BtTips: typeof import('./../src/components/base/bt-tips/index.vue')['default']
    Message: typeof import('./../src/components/utils/message/index.tsx')['default']
    MessageList: typeof import('./../src/components/utils/message/message-list.tsx')['default']
    Method: typeof import('./../src/components/utils/confirm/method.tsx')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NModal: typeof import('naive-ui')['NModal']
    NPagination: typeof import('naive-ui')['NPagination']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTable: typeof import('naive-ui')['NTable']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
