// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package operation_log

import (
	"billionmail-core/api/operation_log"
)

type ControllerV1 struct{}

func NewV1() operation_log.IOperationLogV1 {
	return &ControllerV1{}
}
