// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package files

import (
	"billionmail-core/api/files"
)

type ControllerV1 struct{}

func NewV1() files.IFilesV1 {
	return &ControllerV1{}
}
