// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dockerapi

import (
	"billionmail-core/api/dockerapi"
)

type ControllerV1 struct{}

func NewV1() dockerapi.IDockerapiV1 {
	return &ControllerV1{}
}
