// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package entity

// BmRelay is the golang structure for table bm_relay.
type BmRelay struct {
	Id             int    `json:"id"              description:""`
	Remark         string `json:"remark"          description:"Remarks"`
	Rtype          string `json:"rtype"           description:"Relay type: gmail, sendgrid, custom, aws, mailgun, local"`
	SenderDomain   string `json:"sender_domain"   description:"Sender domain, e.g., \"@example.com\""`
	RelayHost      string `json:"relay_host"      description:"Relay server address"`
	RelayPort      string `json:"relay_port"      description:"Relay server port, e.g., \"587\""`
	AuthUser       string `json:"auth_user"       description:"SMTP authentication username"`
	AuthPassword   string `json:"auth_password"   description:"SMTP authentication password (consider encrypted storage)"`
	Ip             string `json:"ip"              description:"IP used to remind users to update SPF records (optional)"`
	Host           string `json:"host"            description:"Host used to remind users to update SPF records (optional)"`
	CreateTime     int    `json:"create_time"     description:""`
	UpdateTime     int    `json:"update_time"     description:""`
	Active         int    `json:"active"          description:"Whether this relay configuration is enabled"`
	AuthMethod     string `json:"auth_method"     description:"Authentication method: LOGIN, PLAIN, CRAM-MD5, NONE"`
	TlsProtocol    string `json:"tls_protocol"    description:"TLS protocol: STARTTLS, SSL/TLS, NONE"`
	SkipTlsVerify  int    `json:"skip_tls_verify" description:"Whether to skip TLS verification: 1-skip, 0-do not skip"`
	HeloName       string `json:"helo_name"       description:"HELO hostname"`
	SmtpName       string `json:"smtp_name"       description:"Unique name of the SMTP server"`
	HeaderJson     string `json:"header_json"     description:"Custom email headers in JSON format"`
	MaxConcurrency int    `json:"max_concurrency" description:"Maximum concurrent connections"`
	MaxRetries     int    `json:"max_retries"     description:"Maximum retry attempts"`
	MaxIdleTime    string `json:"max_idle_time"   description:"Maximum idle connection time"`
	MaxWaitTime    string `json:"max_wait_time"   description:"Maximum wait time"`
}
