// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package entity

type BmRelayConfig struct {
	Id            int    `json:"id"              description:""`
	Remark        string `json:"remark"          description:"Remark"`
	Rtype         string `json:"rtype"           description:"Relay type: gmail, sendgrid, custom, aws, mailgun, local"`
	RelayHost     string `json:"relay_host"      description:"Relay server address"`
	RelayPort     string `json:"relay_port"      description:"Relay server port, e.g. \"587\""`
	AuthUser      string `json:"auth_user"       description:"SMTP auth username"`
	AuthPassword  string `json:"auth_password"   description:"SMTP auth password (encrypted)"`
	Ip            string `json:"ip"              description:"IP for reminding user to update SPF record (optional)"`
	Host          string `json:"host"            description:"Hostname for reminding user to update SPF record (optional)"`
	HeloName      string `json:"helo_name"       description:"HELO hostname"`
	SkipTlsVerify int    `json:"skip_tls_verify" description:"Skip TLS verification: 1-skip, 0-do not skip"`
	SmtpName      string `json:"smtp_name"       description:"SMTP server unique name"`
	CreateTime    int    `json:"create_time"     description:"Creation time"`
	UpdateTime    int    `json:"update_time"     description:"Update time"`
	Active        int    `json:"active"          description:"Whether this relay config is enabled: 1-enabled, 0-disabled"`
	AuthMethod    string `json:"auth_method"     description:"Authentication method: LOGIN, PLAIN, CRAM-MD5, NONE"`
}
