// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package entity

type BmRelayDomainMapping struct {
	Id           int    `json:"id"            description:""`
	RelayId      int    `json:"relay_id"      description:"Reference to id in bm_relay_config table"`
	SenderDomain string `json:"sender_domain" description:"Sender domain, e.g. \"@example.com\""`
	CreateTime   int    `json:"create_time"   description:"Creation time"`
}
