// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package settings

import (
	"billionmail-core/api/settings"
)

type ControllerV1 struct{}

func NewV1() settings.ISettingsV1 {
	return &ControllerV1{}
}
