// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package relay

import (
	"billionmail-core/api/relay"
)

type ControllerV1 struct{}

func NewV1() relay.IRelayV1 {
	return &ControllerV1{}
}
