// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package mail_boxes

import (
	"context"
	"strings"

	"billionmail-core/api/mail_boxes/v1"
)

type ControllerV1 struct{}

func New() *ControllerV1 {
	return &ControllerV1{}
}
