// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package mail_boxes

import (
	"billionmail-core/api/mail_boxes"
)

type ControllerV1 struct{}

func NewV1() mail_boxes.IMailBoxesV1 {
	return &ControllerV1{}
}
